package com.audiobook.service;

import com.audiobook.dto.AudiobookSeedDto;
import com.audiobook.model.Audiobook;
import com.audiobook.repository.AudiobookRepository;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;

@Component
public class DataSeederService implements CommandLineRunner {
    
    private static final Logger logger = LoggerFactory.getLogger(DataSeederService.class);
    
    @Autowired
    private AudiobookRepository audiobookRepository;
    
    @Override
    @Transactional
    public void run(String... args) {
        if (audiobookRepository.count() == 0) {
            logger.info("Seeding sample audiobooks...");
            seedAudiobooks();
            logger.info("Sample audiobooks seeded successfully!");
        } else {
            logger.info("Database already contains audiobooks. Skipping seed.");
        }
    }
    
    private void seedAudiobooks() {
        try {
            ClassPathResource resource = new ClassPathResource("data/sample-audiobooks.json");
            InputStream inputStream = resource.getInputStream();
            
            ObjectMapper objectMapper = new ObjectMapper();
            List<AudiobookSeedDto> seedDtos = objectMapper.readValue(
                inputStream,
                new TypeReference<List<AudiobookSeedDto>>() {}
            );
            
            List<Audiobook> audiobooks = seedDtos.stream()
                .map(this::toAudiobook)
                .toList();
            
            audiobookRepository.saveAll(audiobooks);
            logger.info("Created {} sample audiobooks from JSON file", audiobooks.size());
            
        } catch (IOException e) {
            logger.error("Failed to load sample audiobooks from JSON file", e);
            throw new RuntimeException("Failed to seed audiobooks", e);
        }
    }
    
    private Audiobook toAudiobook(AudiobookSeedDto dto) {
        // Use constructor with all required fields
        // Auto-generated fields (id, createdAt, updatedAt) will be set by JPA
        // Collections will be initialized as empty sets
        return new Audiobook(
            null, // id - auto-generated by JPA
            dto.getTitle(),
            dto.getAuthor(),
            dto.getDescription(),
            dto.getNarrator(),
            dto.getDurationMinutes(),
            new BigDecimal(dto.getPrice()),
            dto.getCategory(),
            dto.getCoverImageUrl(),
            generateAudioFileUrl(dto.getTitle()),
            dto.getRating(),
            dto.getReviewCount(),
            LocalDateTime.now().minusMonths((long)(Math.random() * 24)), // publishedDate
            null, // createdAt - set by @PrePersist
            null, // updatedAt - set by @PrePersist
            new HashSet<>(), // libraryItems - empty set
            new HashSet<>()  // purchases - empty set
        );
    }
    
    private String generateAudioFileUrl(String title) {
        return "https://example.com/audio/" + title.toLowerCase().replaceAll(" ", "-") + ".mp3";
    }
}
